### ISSUE TITLE
Add guidance around use of tags

### ISSUE THREAD

**Issue by obsidianforensics** [forensicswiki/wiki#11]
As part of the migration from the MediaWiki we needed to move from Categories and Sub-Categories to Tags, which work a little differently. One consideration with tags is the number of them; if the tags are too specific we'll end up with thousands of tags, and if they are too generic they'll lose meaning (neither of which is helpful). 

A document around the expected usage of tags would help address this. It could be its own separate page or part of the contributing guide.

**Comment by rjcolonna** [comment]
Hi @simsong,
I created  [tag guideline](https://forensics.wiki/community/#tag-guidelines) section.  I was hoping to get your feedback on the approach we are taking.  Is there anything we could do to make it more efficient?

**Comment by rjcolonna** [comment]
Guidance for TAGS added in [PR](https://github.com/forensicswiki/wiki/pull/17)
