### ISSUE TITLE
Change repo name

### ISSUE THREAD

**Issue by obsidianforensics** [forensicswiki/wiki#13]
We created this repo as a test (hence the name) but that test has gone well :). We need to move the content to be under a better name (`wiki` perhaps?). 

We could do this in a few ways:
- Export content from here, import into `wiki`
- Rename this repo
- Migrate using git commands (perhaps like https://itnext.io/git-repository-transfer-keeping-all-history-670fe04cd5e4)

**Comment by simsong** [comment]
Renaming repos is well supported. That’s what I recommend.

**Comment by obsidianforensics** [comment]
I deleted the old mostly-empty `wiki` repo, and renamed this one to `wiki`. I'll wait a bit and see if any of the domain stuff breaks (it _shouldn't_, but we'll see).

**Comment by obsidianforensics** [comment]
All seems to be working 👍
