### ISSUE TITLE
href parse error

### ISSUE THREAD

**Issue by nblog** [forensicswiki/wiki#179]
https://github.com/forensicswiki/wiki/blob/63a817385aa707bea9868e783c5a47fe8ef3e60f/docs/index.md?plain=1#L72

```
<ui><li><a href="tags/#file_analysis">File Analysis</a>: <a href="bless">bless</a>, <a href="ghidra">ghidra</a>, <a href="pst_file_viewer>PST File Viewer</a>, <a href="hachoir">hachoir</a></ui></li>
```

missing separator between `PST File Viewer` and `hachoir`.
`> PST File Viewer<`(useless space), but not relevant, 😂

**Comment by obsidianforensics** [comment]
Thanks for flagging!
