### ISSUE TITLE
Images broken in pages with <figure>

### ISSUE THREAD

**Issue by obsidianforensics** [forensicswiki/wiki#30]
It seems the image paths didn't get translated correctly on pages where the image is displayed via HTML rather than Markdown. The path to the image either needs to be changed, or the format changed to Markdown. I think moving it to be Markdown wherever possible is preferred. 

Example: 
- https://forensics.wiki/atola_taskforce/

**Comment by simsong** [comment]
Are all of the images in a single directory?

**Comment by obsidianforensics** [comment]
Yes, `/assets/images/` I believe.

**Comment by simsong** [comment]
Okay, just have a hard-coded directory in a config file somewhere and fix all of the paths on HTML generation?
