### ISSUE TITLE
Remove links that define "wikilink" 

### ISSUE THREAD

**Issue by joachimmetz** [forensicswiki/wiki#73]
Not 100% sure but the use of "wikilink" in a link seems to be a left over from MediaWiki. It causes broken links in some cases. At the moment I see no added value of using "wikilink". So I opt to remove it.

@rjcolonna @obsidianforensics thougths?

**Comment by joachimmetz** [comment]
Along similar lines `User:` and `Talk:` links as well

**Comment by rjcolonna** [comment]
Yes, You are correct @joachimmetz  the "wikilink" link is left over from MediaWiiki.  We had a script that removed the majority of them but I am sure there are a few that might still exist.  They should be replaced so the links work.

**Comment by joachimmetz** [comment]
@rjcolonna thanks for that context, I'll work on replacing them.

**Comment by joachimmetz** [comment]
Wikilink addressed, but one strange edge case remaining https://github.com/forensicswiki/wiki/issues/81

**Comment by joachimmetz** [comment]
https://github.com/forensicswiki/wiki/issues/81 has been addressed with thanks to @rjcolonna, closing issue
