### ISSUE TITLE
Merge multiple articles about oxygen_forensic_suite

### ISSUE THREAD

**Issue by joachimmetz** [forensicswiki/wiki#74]
There are multiple articles about oxygen_forensic_suite, merge them into a single article

**Comment by rjcolonna** [comment]
We should do this for the Windows articles as well.
[Windows](https://forensics.wiki/windows/)
[Windows Vista](https://forensics.wiki/windows_vista/)
[Windows 7](https://forensics.wiki/windows_7/)
[Windows 8](https://forensics.wiki/windows_8/)
[Windows 10](https://forensics.wiki/windows_10/)

**Comment by joachimmetz** [comment]
I recall that for windows the reason for splitting was the numerous new subsystems/features added and otherwise the main article became too long. The oxygen_forensic_suite ones seem to be mostly duplication

**Comment by joachimmetz** [comment]
So https://forensics.wiki/oxygen_forensic_suite_2/ is an older version of https://forensics.wiki/oxygen_forensic_suite_2014/ and there are links to a non-existing https://forensics.wiki/oxygen_forensic_suite_2010/. I'll consolodate everything under https://forensics.wiki/oxygen_forensic_suite/ and keep oxygen_forensic_suite_2 and oxygen_forensic_suite_2014 as redirects.
