### ISSUE TITLE
Conversion error in fileobject article?

### ISSUE THREAD

**Issue by joachimmetz** [forensicswiki/wiki#81]
He @rjcolonna not urgent, hope you can help shed some light on this in https://forensics.wiki/fileobject/ there is the following

```
<run[:Category:Operating systems](:Category:Operating_systems "wikilink") file_offset='0' fs_offset='37376' img_offset='37888' len='43'/>
```

`[:Category:Operating systems](:Category:Operating_systems "wikilink")` looks out of place. Thoughts?

**Comment by rjcolonna** [comment]
Interesting.  I am not sure what went wrong here.  Initially, I thought it was a conversion error.  I checked the original export of the mediawiki version to see if it was wrong when we got it.

```
&lt;byte_runs&gt;
       &lt;run file_offset='0' fs_offset='37376' img_offset='37888' len='43'/&gt;
      &lt;/byte_runs&gt;
      &lt;hashdigest type='md5'&gt;2bbe5c3b554b14ff710a0a2e77ce8c4d&lt;/hashdigest&gt;
      &lt;hashdigest type='sha1'&gt;b3ccdbe2db1c568e817c25bf516e3bf976a1dea6&lt;/hashdigest&gt;
```

It looks right.

I checked the export after it was converted to markdown.  It showed it was  exactly the same as the mediawiki version:

```
         <byte_runs>
           <run file_offset='0' fs_offset='37376' img_offset='37888' len='43'/>
          </byte_runs>
          <hashdigest type='md5'>2bbe5c3b554b14ff710a0a2e77ce8c4d</hashdigest>
          <hashdigest type='sha1'>b3ccdbe2db1c568e817c25bf516e3bf976a1dea6</hashdigest>
```

I'll submit a PR to remove it.
